language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install -g bower polymer-cli
- bower install
addons:
  sauce_connect: true
script:
- polymer lint -i variables-editor.html variables-item.html
- wct --plugin sauce
cache:
  directories:
  - bower_components
  - node_modules
env:
  global:
  - secure: h7gD/ZNTyuQuhXnY3FIGcEfH7baF2alzMyLrUVfOBCG4FGwHljDqESqH98hbyq7uaDi8My4GDZdm9l1DqQXt6FiOmCaDRbwnP0u7b1NixFgf0MqSUpyq9Q+9gZcc7DRgzoA6EWP5wksp67R6mlfarDVM7RXlKD09MjHud2Mb/kf1r6bjW89FlmJ0rOXIPEa97tZmZ/k8pIcurW72VNoAE6KKkanw2OdImpVYUVVJ7cuQLVqsz/Fl0DFx4PvIAkzZqx6M4uKDtqzYczHCiywN6TjJUzinwAjeyej4ZywISW0BnUkHFaKncZ71rqsv7/TctlwhFLjtoyJ4HiYADuC/exffvrqEqXYu4TCS0uAF/RbPvx7pUy9tR3DB/+/7DZwgTXjuJWH2jb/I8wjUOJaPzRbuE925Yh/YNQmZxJUmwziVAUWBoAEADjFJYcOnnbXK/xA0RLl3wVb/xVdNiBoBofYsFNnk60J24gOZ27MjL9z8q4HlwnnRmUSoJh4hr+MpM8SyH6puqCJ0UNws44NTOQr5slOV+hqWVsGCQ9Qu0web7iWV+Cs1rvf7RIkEKgmIEp7N5oi9k/+rpZZJKxfO0HA3ALJk7g1OeQIRMJ49H8Wo2oUBW+MVg8XqiV2KMZYW5N+ObS3S0z6hUnd3LOSPxKiHFt9TFHMD/QmhPb7woAk=
  - secure: n6XsaKUpCHiVbLv1RzqTX3khoJrXegBoQj01QY34Fho9683hfEqQ4G6x28VaSae6vUnfHMFZopkFNEI7a3JAT/KSrtoaBtKNWsx3E8Sa1Rt36CvHYDJPWv70HSissv4G71EoCPrbNg0e3ilQmthpRlV2TlOg6+bJeUmnJeqQ5o4GI1zSt6jJriy8I6ngnhGRW7kQ8w/REDrfhhrG1uUtlhOGcQBQtfwjjHqIjmBcw3r0IpfG+VObM/GKGEF8BRUjCchVOGdw4wgW/QprZJ0UMoKKnzGLanDyZcmojT9RUjFvUIwJCiU5UZALhNIF5klg/7qu4iXPMlQYXHFKCaD2RZZ9YJmnRs2fpOPD5fG4W/5ztAdUWQOs2MZ/AvAuZZXUircqmn2msL6rDbp8iorJJOpM11M4q0YamB2aaunMh62dZPco1ulbMeQKz6vq/B86AqyRNeAMz2XwzmjJXM0iPVdoZO5su/YNn16dnyCkCltMo5+xa+8ZF8i+yJqlW72BZf84Hjq6OcdNFFDcxYjJmEpWLZ48aXfsD0EQpgDE5TtLSfFDAhPl8aVxlZgYbfF9t/lIzwbcgYunav0gaiwDnUMqVGmjPOCxt0FTcysPw2KYJevtyyg+zJTrwvyGPGSdyXpMrq1GZf6REr2F+I72wOYZ1VAg3MqUzijaarnYhNA=
