language: node_js
sudo: required
dist: trusty
node_js: stable
before_script:
- npm install -g bower polymer-cli
- bower install
addons:
  sauce_connect: true
script:
- polymer lint -i variables-editor.html variables-item.html
- wct --plugin sauce
cache:
  directories:
  - bower_components
  - node_modules
