/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   variable-editor-dialog.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../paper-dialog/paper-dialog.d.ts" />
/// <reference path="../paper-dialog-scrollable/paper-dialog-scrollable.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-input/paper-input.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-toast/paper-toast.d.ts" />
/// <reference path="../paper-tabs/paper-tab.d.ts" />
/// <reference path="../paper-tabs/paper-tabs.d.ts" />
/// <reference path="../iron-pages/iron-pages.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />

declare namespace UiElements {

  /**
   * Dialog to edit a variable.
   */
  class VariableEditorDialog extends Polymer.Element {

    /**
     * Value of the variable.
     */
    value: string|null|undefined;

    /**
     * True if the dialog should be opened.
     */
    opened: boolean|null|undefined;

    /**
     * Selected documentation page
     */
    selectedDoc: number|null|undefined;
    docs: any[]|null|undefined;
    evaluated: string|null|undefined;
    _selectedDocChanged(selectedDoc: any): void;
    _evaluate(): void;
    _insertFunction(e: any): void;
    _onClosed(e: any): void;
  }
}

interface HTMLElementTagNameMap {
  "variables-editor-dialog": UiElements.VariableEditorDialog;
}
