/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/VariableEditorDialog.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {AnypointDialog} from '@anypoint-web-components/anypoint-dialog/src/AnypointDialog.js';

import {html, css} from 'lit-element';

export {VariableEditorDialog};

declare namespace UiElements {

  /**
   * Dialog to edit a variable.
   */
  class VariableEditorDialog extends AnypointDialog {

    /**
     * Selected documentation page
     */
    selectedDoc: number|null|undefined;

    /**
     * Value of the variable.
     */
    value: string|null|undefined;
    docs: any[]|null|undefined;

    /**
     * Evaluated variable value
     */
    evaluated: string|null|undefined;
    render(): any;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _selectedDocChanged(selectedDoc: any): void;
    _evaluate(): any;

    /**
     * Handler for list item cloick.
     * Processes event if the target is the button.
     */
    _processFunctionInsertClick(e: ClickEvent|null): void;
    _insertFunction(model: any): void;

    /**
     * Hanlder for dialog's close event
     */
    _onClosed(e: CustomEvent|null): void;
    _valueHandler(e: any): void;
    _docSelectHandler(e: any): any;
  }
}
